name: mario/less tests
on: [push]
jobs:
  Test-Mario-Less:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: docker://cs50/ide:checks
    #   with:
    #     entrypoint: /run_check50.sh
    #     check50_args: "--local --output=json --output-file=results.json cs50/problems/2021/x/mario/less"
    #   env:
    #     CHECK50_PATH: /tmp/check50
    - uses: education/autograding@v1
